### ISSUE TITLE
bug 🐛 v1.0.6 not compatible with action/deploy-pages v4 — isn't able to upgrade to node v20

### ISSUE THREAD

**Issue by murtuzaalisurti** [withastro/action#40]
I want to bump the `action/deploy-pages` version to `v4` as it supports node 20 (https://github.com/actions/deploy-pages/pull/256) but I am unable to do so because the current version of `withastro/action@v1.0.6` is not compatible with it. I get this while running the workflow:

```console
Fetching artifact metadata for "github-pages" in this workflow run
Found 0 artifact(s)
Error: Fetching artifact metadata failed. Is githubstatus.com reporting issues with API requests, Pages, or Actions? Please re-run the deployment at a later time.
Error: Error: No artifacts named "github-pages" were found for this workflow run. Ensure artifacts are uploaded with actions/artifact@v4 or later.
    at getArtifactMetadata (/home/runner/work/_actions/actions/deploy-pages/v4.0.3/src/internal/api-client.js:85:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4.0.3/src/internal/deployment.js:66:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4.0.3/src/index.js:30:1)
Error: Error: No artifacts named "github-pages" were found for this workflow run. Ensure artifacts are uploaded with actions/artifact@v4 or later.
```

warning from github actions while using `action/deploy-pages@v3`:

```console
[build](https://github.com/murtuzaalisurti/murtuzaalisurti.github.io/actions/runs/7684619378/job/20941330307)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by irian-codes** [comment]
Yep, getting this warning too. Great PR, hopefully they'll accept it!

**Comment by basher** [comment]
Any updates?

I'm now unable to publish changes to my website, and cannot revert back to Node 16 as Github actions don't support it.

**Comment by murtuzaalisurti** [comment]
resolved now!
